name: Gerar APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Gerar APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2

      - name: Configurar ambiente Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Gerar número de versão
        id: version
        run: echo "VERSION_CODE=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Construir APK admin
        run: ./gradlew :admin:assembleDebug --versionCode=$VERSION_CODE

      - name: Salvar APK admin como artefato
        uses: actions/upload-artifact@v2
        with:
          name: app-debug-$VERSION_CODE.apk
          path: app/build/outputs/apk/debug/app-debug.apk